export * from './Intro';
export * from './Skills';
export * from './Projects';
export * from './Contact';
export * from './WorkExp';
export * from './Education';
export * from './Certifications';
export * from './Header';
export * from './Footer';
